language: cpp

branches:
  only:
    - master
    - coverity_scan
    - gh-pages-dev
    - website-dev

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.2

env:
  - PATH=/opt/qt56/bin:/usr/local/opt/qt5/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt563-trusty'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5
      - qt56base
      - libgl1-mesa-dev

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew unlink qt@4; brew update; brew reinstall qt5; fi

script:
  - mkdir build
  - cd build
  - qmake ../gui/qt && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5
  - cd ../core
  - make clean && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 all
  - cd ../tests/autotester
  - make clean && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 all
